title: Keiya's Blog
name: Keiyas 
email: eduardo.edu.hdez@gmail.com
description: Hello there! I'm Keiyas a Canary DevOps based in Barcelona. 
baseurl: "/blog"
url: ""

display_footer: none

parallax_image_one: assets/images/startup3.jpg
parallax_image_two: assets/images/startup3.jpg

project_one: This blog!
project_one_description: Keiya's personal webpage.
project_one_url: https://keiyasssss.github.io/jekyll-blog/
project_one_icon: location_on

portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: amazonwebservices
  - name: bitbucket
  - name: bootstrap
  - name: bower
  - name: chrome
  - name: confluence
  - name: css3
  - name: debian
  - name: devicon
  - name: docker
  - name: gimp
  - name: git
  - name: github
  - name: gitlab
  - name: inkscape
  - name: itellij
  - name: java
  - name: javascript
  - name: linux
  - name: mysql
  - name: nginx
  - name: nodejs
  - name: oracle
  - name: photoshop
  - name: postgresql
  - name: python
  - name: pycharm
  - name: redhat
  - name: ssh
  - name: tomcat
  - name: travis
  - name: trello
  - name: twitter
  - name: ubuntu
  - name: vim
  - name: visualstudio
  - name: wordpress

icon_size: 50 
colored: colored

project_button: Github

github: https://github.com/keiyasssss/jekyll-blog/

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: UA-55172930-2

cookies_banner: show

cookie_accept_message: Thanks!

syntax_highlighting: true

markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
